enum intrinsicActionTypes {
  CASH_FLOW_INPUT_CHANGE = 8678,
  CALCULATE_INTRINSIC_VALUE,
  VALIDATE_FIELDS,
  RESET_VALUES,
  ON_PASSWORD_INPUT_CHANGE,
  INTIAL_INVESTOR_DETAILS,
  TRANSLATE
}

export default intrinsicActionTypes;
